broadcast:
  interval: 100
  content:
  - §6请您输入/l <密码>以验证您的账户
  - §6或者/reg <密码> <密码>以设置密码
binding:
  command: true
  # 多行以分号';'隔开
  # 变量$p自动替换成玩家名
  execute: []
minimal: false
log: true
kick: 600
notify:
  mail: true